-- GTFS Static (Metro only) exploration

SELECT COUNT(*) AS routes_count
FROM TRAFIK_DATA.STATIC.METRO_ROUTES;

SELECT COUNT(*) AS trips_count
FROM TRAFIK_DATA.STATIC.METRO_TRIPS;

SELECT COUNT(*) AS stop_times_count
FROM TRAFIK_DATA.STATIC.METRO_STOP_TIMES;

SELECT COUNT(*) AS stops_count
FROM TRAFIK_DATA.STATIC.METRO_STOPS;

-- Sample routes
SELECT *
FROM TRAFIK_DATA.STATIC.METRO_ROUTES
LIMIT 10;

-- Sample stops
SELECT *
FROM TRAFIK_DATA.STATIC.METRO_STOPS
LIMIT 10;
