SELECT * 
FROM TRAFIK_DATA.STAGING.SL_DEPARTURES_RAW
LIMIT 10;

SELECT *
FROM TRAFIK_DATA.STAGING.STG_SL_DEPARTURES
LIMIT 10;

SELECT *
FROM TRAFIK_DATA.MART.SL_DEPARTURES_MART
ORDER BY ingested_date DESC
LIMIT 20;



SELECT _site_id, SUM(departures_count) AS total_departures
FROM TRAFIK_DATA.MART.SL_DEPARTURES_MART
GROUP BY _site_id
ORDER BY total_departures DESC
LIMIT 5;



SELECT MAX(ingested_at_ts) AS latest_ingest
FROM TRAFIK_DATA.STAGING.STG_SL_DEPARTURES;