USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS DLT_USER
  PASSWORD = '123456Faze'
  DEFAULT_ROLE = ETL_DLT_ROLE
  DEFAULT_WAREHOUSE = TRAFIK_WH
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS DBT_USER
  PASSWORD = '123456Faze'
  DEFAULT_ROLE = TRANSFORM_DBT_ROLE
  DEFAULT_WAREHOUSE = TRAFIK_WH
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS BI_USER
  PASSWORD = '123456Faze'
  DEFAULT_ROLE = BI_ROLE
  DEFAULT_WAREHOUSE = TRAFIK_WH
  MUST_CHANGE_PASSWORD = FALSE;






--Grants
  USE ROLE SECURITYADMIN;

-- DLT
GRANT ROLE ETL_DLT_ROLE TO USER DLT_USER;
GRANT USAGE ON WAREHOUSE TRAFIK_WH TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON DATABASE TRAFIK_DATA TO ROLE ETL_DLT_ROLE;
GRANT USAGE, CREATE TABLE ON SCHEMA TRAFIK_DATA.STAGING TO ROLE ETL_DLT_ROLE;

-- DBT
GRANT ROLE TRANSFORM_DBT_ROLE TO USER DBT_USER;
GRANT USAGE ON WAREHOUSE TRAFIK_WH TO ROLE TRANSFORM_DBT_ROLE;
GRANT USAGE ON DATABASE TRAFIK_DATA TO ROLE TRANSFORM_DBT_ROLE;

GRANT USAGE ON SCHEMA TRAFIK_DATA.STAGING TO ROLE TRANSFORM_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA TRAFIK_DATA.WAREHOUSE TO ROLE TRANSFORM_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA TRAFIK_DATA.MART TO ROLE TRANSFORM_DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TRAFIK_DATA.STAGING TO ROLE TRANSFORM_DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TRAFIK_DATA.WAREHOUSE TO ROLE TRANSFORM_DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA TRAFIK_DATA.MART TO ROLE TRANSFORM_DBT_ROLE;

-- BI
GRANT ROLE BI_ROLE TO USER BI_USER;
GRANT USAGE ON DATABASE TRAFIK_DATA TO ROLE BI_ROLE;
GRANT USAGE ON SCHEMA TRAFIK_DATA.MART TO ROLE BI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA TRAFIK_DATA.MART TO ROLE BI_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA TRAFIK_DATA.MART TO ROLE BI_ROLE;