[destination.snowflake.credentials]
database = "TRAFIK_DATA"
username = "ABDIRAHMANHASSAN47"
host = "FMVXUQS-IF87024"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9CqZu/O0dCNWL
VGJC8r5ViZMaHclF25lvVZ//ky1d3v09bZ8IzaW/UI9zYhN2BDY3GlHJ5BlKxKUh
dD3amLzEDyJCFp07+hI6SFBb+AWQbsov5hoZuthtbht+74snVXo6EBv2KZF5vlEt
DVeDG3sj9gEdJqJ/K1UkA8kix4C7kNxOX9EpNrM2DGTgoxQbeK6ybCk1cS34scUN
NpDYeuwpu9REz+Ztl2XflNA/N59XOvTOxBgweyOSDe91OsAXOAJiEGY1bqAqlm1E
cH4uStSQUz7uCJGuDtPEmAC3f6QFbmstz1IAiXA3OKjztcNessJIaejYDIom9e2g
C3TvCUBJAgMBAAECggEAAb6RKhmF45xzAgHhlT4RsQ7fr2BCfPVJjWw0GYLlaoYV
/qTeEJH7O1B2PmmTheWEjY4d3pfO/vBhGLWuo2+A4GtGVOdKBKVqWSTVLwATJxHK
plYAfCfL+viG4u05cr+4bMQ8ydD44W925sxGeDR+9qY8vOTgH33KH5a0WrCOGMz5
mBVfYRfJ1+EgFtEUKitTiD35fjwZdEj58Rav1YMnqGttK2K58Da7451q2h75VXjf
gY2uZ0x89bhiU+irY5idLbudfj4bKYex+nGq9Z34j0vm+NkbSVe+0qnjMRGiy72Q
nGSI4HSQVJ9sK95yF1gZVghPPN5JMUyAZFt32SKXoQKBgQDdLf5BKyCN4N87jGld
Vhn7I5Jav3L1F2Cyw2mnbJBDFy9KbqgaK7UXlRQ0af5c0HR3d1s4l6FVANWklvmI
hfB4eEewnWn5Evuca73LZdKMW/mToTTE6hCGddDfDYGKVZebN5O7HF/WJM5MyO0X
jdliZ6MRfyrzVgO9FbkKd15pkQKBgQDazWzm5ILA1IB2SoYhV2rkbAe+ExwXfLPs
5zgmMFb1BqkTEf4tAqGZz5x0qPR9fvZVXobXWdKbXRzBsiAShVHLKyrtvklFJJOC
lHt/H7PJ8XuGyf1VaX8Gi/a1vLECI6zBYBsXekDDXz7zlzV65/H01FVHPSTe2Yq2
yoNu+XBPOQKBgGcoGlt+p9JEPRli5Yl4rOlqr8nPXOhenOUDKvXBNo9z8sR+U7zR
Accb6q5/ePkE6C0H5+2/Gqmwl/QJzhwUjBFD1/vRjylx5xQPVBfXR5nbE83888Wb
fVWZAW/mtrI0NV9ZTneIRlJ0HBvH4nyH1gmFWJLCgt+3EEtSJFlzTv9hAoGBAKd3
zd+XjSBsRXrEpY8FarI0oWRxGfI8Jzau7sIEA7p9A5GuFt56ghfI2NZNrvwS3hYP
SKOxg0oY5Xa3kGa8lhMsEipvl4MNcL3kSfXN3P03EDXlijoCihAHtqf5KX4ashI8
LeA1WTZwQy2MUYml2AJtNmxVN1A+LzajICAjWTu5AoGAIzdcT7LUVRyJYQK1MNSc
7fgLT21yqzx7TV0MTu2aq9xN8jGAeDCk/cmTGvrf0mIquySKKVeYcCqo7ps/alA7
x0MvX1pkaP6ZiAxxuSYP04vNmLLfsxOxUIids8MWzvw1qFAt/CG61pcQZvE3mQ5Z
QK+Xl8oDWcTkBubf4IP/XFU=
-----END PRIVATE KEY-----
"""
