[snowflake]
account = "FMVXUQS-IF87024"
user = "ABDIRAHMANHASSAN47"
role = "TRANSFORM_DBT_ROLE"
warehouse = "TRAFIK_WH"
database = "TRAFIK_DATA"
schema = "MART"
private_key_path = "C:/Users/Abdirahman/Documents/github/Examensarbete_DE24/.keys/snowflake_key.p8"
# private_key_passphrase = ""
